"""Add is_complited field to tasks

Revision ID: 01b6f012adb6
Revises: 477f1dda8848
Create Date: 2026-03-29 19:02:52.250980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b6f012adb6'
down_revision: Union[str, Sequence[str], None] = '477f1dda8848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column(
        'is_completed', sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
                  )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_completed')
    # ### end Alembic commands ###
