"""Add is_superuser and is_active fields to user model

Revision ID: 18c7684f41a3
Revises: 01b6f012adb6
Create Date: 2026-03-30 18:06:53.343429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c7684f41a3'
down_revision: Union[str, Sequence[str], None] = '01b6f012adb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'is_active',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
                  )
    op.add_column('users', sa.Column(
        'is_superuser',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
                  )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
